### PR TITLE
95 fix date fields into dropdown

### PR DESCRIPTION
**Pull request by Divinare**
Relates to: https://github.com/HSLdevcom/bultti/issues/95

FE PR: https://github.com/HSLdevcom/bultti/pull/169

I realized that we have a inspectionValidator so I moved code here there: https://github.com/HSLdevcom/bultti/pull/169/commits/a4d91bb97eacab49651d092ca5235127f4881155 

Can't test that validation though because pre/post inspection creation is not working for me locally. Need to check it via screenshare at some point

### CODE REVIEW

**Review by danieldunderfelt — APPROVED** [review]
Looks good!

**Comment by Divinare** [comment]
Did some refactoring here as you can see ^

**Comment by Divinare** [comment]
Review fixes done ^

**Review by danieldunderfelt — APPROVED** [review]
Nice!

**Pull request merged**
