### PR TITLE
318 fix execution requirement percentage when editing

### PR DESCRIPTION
**Pull request by danieldunderfelt**
Closes https://github.com/HSLdevcom/bultti/issues/318

Execution requirement percentages were not updating correctly after being edited. I'm not 100% sure of the cause, but I suspect an Apollo cache issue. it seems to work with the changes in this PR.

The issue was when editing Execution Requirement quotas for equipment. Editing percentage values (double-click the quota cell) should change the total value, which didn't happen. Adding or removing equipment should recalculate all other quotas to keep the same percentage as before the operation.

UI PR (schema updates): https://github.com/HSLdevcom/bultti-ui/pull/97

- Clean up quota value update resolvers
- Return ExecutionRequirementQuota and EquipmentCatalogueQuota from these instead of Equipment (this seems to fix the issue)

### CODE REVIEW

**Comment by Divinare** [comment]
Tested these:

* Editing a percentage quota in the equipment table of an execution requirement should be reflected in the total sum for the column. This was broken.
    * Editing percentage to a number > 0 worked e.g. 5% -> 6%
        * here, the total value seemed to work as well!
    * Editing percentage as 0 **didnt work,** e.g. 5% -> 0% failed, after saving it appeared again as 5%
    * Editing percentage as negative did work (**however, i think this shouldn't work**), e.g. 5% -> -15% worked. Shouldn't negative number be casted as 0?
    
* Adding or removing equipment should recalculate all other quotas to keep the percentage the same. This worked as far as I could tell.
   * This seemed to work nicely!
* The total percentage should also reflect equipment added in previous inspections.
   * Sadly couldnt bring equipment added in the previous preInspection. **Added a card for this:** https://github.com/HSLdevcom/bultti/issues/339
* Editing quotas and kilometers in the Equipment Catalogue should also work, which it does.
    * Editing percentages of the Equipment Catalogue does work in procurementUnit page
    * Editing inspection's execution_requirement_quota's meterRequirement (metriosuus) **throw me an error page**: Unhandled Rejection (Error): Response not successful: Received status code 400

Additional notes:
* At least for me, I have to double double click to edit a cell. I mean the first double click does select the cell but backspace for example doesn't work. **I have to double click again** to really edit something.

**Comment by danieldunderfelt** [comment]
> Editing a percentage quota in the equipment table of an execution requirement should be reflected in the total sum for the column. This was broken.

This was what this PR was supposed to fix :( I'll revisit it.

> At least for me, I have to double double click to edit a cell. I mean the first double click does select the cell but backspace for example doesn't work. I have to double click again to really edit something.

Tried to fix this, couldn't find and fix the issue within a reasonable timeframe.

**Comment by Divinare** [comment]
Everything now works except editing two or more values at once. E.g. putting two values 0 -> 5 or putting two values 5 -> 0, it only changes one of the values when saving.

**Review by Divinare — APPROVED** [review]
Works now as expected!

**Pull request merged**
