### PR TITLE
Cypress init

### PR DESCRIPTION
**Pull request by Divinare**
FE PR: https://github.com/HSLdevcom/bultti-ui/pull/49

* Added possibility to change user role on the fly (when isTesting arg is passed into login() resolver
* Note: UserResolver.currentUser now returns currentUser on purpose because that's what we want: to return the in memory user that can be overridden by a new role. Don't know if there's any better way for this current setup. Other option would be to reconstruct this whole user management idea but that's out of scope of this task.

### CODE REVIEW

**Review by danieldunderfelt — CHANGES_REQUESTED** [review]
Looks good, just a few comments.

**Comment by Divinare** [comment]
Review fixes done ^

Reverted that !DEBUG rule and made a card: https://github.com/HSLdevcom/bultti/issues/195

**Comment by Divinare** [comment]
Now user is blocked if his role is blocked.

Unfortunately couldn't solve the errors when logging in as blocked user. Since it's not that easily done, it can be done here: https://github.com/HSLdevcom/bultti/issues/195

**Review by danieldunderfelt — APPROVED** [review]
LGTM!

**Pull request merged**
